TODO

-monitor data deconne quand pas de context
	+- corrigé, mais c'est pas encore génial
	
-parfois un "not a list of bytes" qui apparait, étrange
	ça provient de pyscard, hexstring?

-quand on déconnecte un lecteur avec une carte connecté, il y a parfois une exception qui saute dans un des threads :/

-on peut ecrire 16 ou 0x16, ce sera accepté par int(,16)

-quand on deconnecte un reader avec une carte connectée :

Failed to disconnect: RPC transport error.
Exception smartcard.Exceptions.CardConnectionException: CardConnectionException('Failed to disconnect: Service not available.',) in <bound method PCSCCardConnection.__del__ of <smartcard.pcsc.PCSCCardConnection.PCSCCardConnection instance at 0x10603ad40>> ignored

   WARNING : the card has been removed, the connection is broken


-rfid>auto con
   WARNING : autoconnect is enable but there is more than one card available

	s'affiche quand il n'y a pas de carte
	
	
	
File "/usr/lib/python2.7/threading.py", line 524, in __bootstrap
    self.__bootstrap_inner()
File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
File "/usr/local/lib/python2.7/site-packages/smartcard/CardMonitoring.py", line 161, in run
    currentcards = self.cardrequest.waitforcardevent()
File "/usr/local/lib/python2.7/site-packages/smartcard/CardRequest.py", line 71, in waitforcardevent
    return self.pcsccardrequest.waitforcardevent()
File "/usr/local/lib/python2.7/site-packages/smartcard/pcsc/PCSCCardRequest.py", line 265, in waitforcardevent
    readernames = self.getReaderNames()
File "/usr/local/lib/python2.7/site-packages/smartcard/pcsc/PCSCCardRequest.py", line 86, in getReaderNames
    raise ListReadersException(hresult)
File "/usr/local/lib/python2.7/site-packages/smartcard/Exceptions.py", line 79, in __init__
    for line in traceback.format_stack():
('Failed to list readers', -2146435043L)
<traceback object at 0xb6817324>
<class 'smartcard.Exceptions.ListReadersException'>
